// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/cdna1/encodings.h"
#include <cstring>
#include <string>

namespace rocjitsu {
namespace cdna1 {

namespace {
std::string flat_mnemonic(std::string_view mnemonic, int seg) {
  // seg: 0=FLAT, 1=SCRATCH, 2=GLOBAL
  if (seg == 1 && mnemonic.substr(0, 5) == "flat_")
    return std::string("scratch_").append(mnemonic.substr(5));
  if (seg == 2 && mnemonic.substr(0, 5) == "flat_")
    return std::string("global_").append(mnemonic.substr(5));
  return std::string(mnemonic);
}
} // namespace

Sop1::Sop1(std::string_view mnemonic, const Sop1MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
  std::memcpy(raw_words_.data(), inst, size_);
  raw_encoding_ = raw_words_.data();
}

bool Sop1::default_encoding() { return inst_.ssrc0 != 255; }

bool Sop1::has_lit_0() { return inst_.ssrc0 == 255; }

Sopc::Sopc(std::string_view mnemonic, const SopcMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
  std::memcpy(raw_words_.data(), inst, size_);
  raw_encoding_ = raw_words_.data();
}

bool Sopc::default_encoding() { return inst_.ssrc0 != 255 && inst_.ssrc1 != 255; }

bool Sopc::has_lit_0() { return inst_.ssrc0 == 255 && inst_.ssrc1 != 255; }

bool Sopc::has_lit_1() { return inst_.ssrc0 != 255 && inst_.ssrc1 == 255; }

bool Sopc::has_lit_0_has_lit_1() { return inst_.ssrc0 == 255 && inst_.ssrc1 == 255; }

Sopp::Sopp(std::string_view mnemonic, const SoppMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Sopp::default_encoding() { return true; }

Sopk::Sopk(std::string_view mnemonic, const SopkMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding() || hasImpliedLiteral())
    size_ += sizeof(MachineInst);
  if (hasImpliedLiteral())
    literal_ = reinterpret_cast<const uint32_t *>(inst)[1];
  std::memcpy(raw_words_.data(), inst, size_);
  raw_encoding_ = raw_words_.data();
}

bool Sopk::default_encoding() { return true; }

bool Sopk::hasImpliedLiteral() { return inst_.op == 20; }

Sop2::Sop2(std::string_view mnemonic, const Sop2MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
  std::memcpy(raw_words_.data(), inst, size_);
  raw_encoding_ = raw_words_.data();
}

bool Sop2::default_encoding() { return inst_.ssrc0 != 255 && inst_.ssrc1 != 255; }

bool Sop2::has_lit_0() { return inst_.ssrc0 == 255 && inst_.ssrc1 != 255; }

bool Sop2::has_lit_1() { return inst_.ssrc0 != 255 && inst_.ssrc1 == 255; }

bool Sop2::has_lit_0_has_lit_1() { return inst_.ssrc0 == 255 && inst_.ssrc1 == 255; }

Smem::Smem(std::string_view mnemonic, const SmemMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Smem::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (inst->soffset_en && inst->imm)
    out += " offset:" + std::to_string(inst->offset);
  if (inst->glc)
    out += " glc";
  if (inst->nv)
    out += " nv";
}

bool Vop1::has_encoded_dpp() const {
  if (!(inst_.src0 == amdgpu::SRC_DPP))
    return false;
  return (inst_.op >= 0 && inst_.op <= 1) || (inst_.op >= 5 && inst_.op <= 8) ||
         (inst_.op >= 10 && inst_.op <= 14) || (inst_.op >= 17 && inst_.op <= 20) ||
         (inst_.op >= 27 && inst_.op <= 36) || inst_.op == 39 ||
         (inst_.op >= 41 && inst_.op <= 47) || (inst_.op >= 51 && inst_.op <= 52) ||
         inst_.op == 55 || (inst_.op >= 57 && inst_.op <= 74) || (inst_.op >= 77 && inst_.op <= 79);
}

Vop1::Vop1(std::string_view mnemonic, const Vop1MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (has_encoded_dpp()) {
    owned_mnemonic_ = amdgpu::dpp::dpp_mnemonic(mnemonic, true);
    display_mnemonic_ = owned_mnemonic_;
  }
  if ((!default_encoding() && !(inst_.src0 == amdgpu::SRC_DPP)) || has_encoded_dpp())
    size_ += sizeof(MachineInst);
  std::memcpy(raw_words_.data(), inst, size_);
  raw_encoding_ = raw_words_.data();
}

void Vop1::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (has_encoded_dpp())
    amdgpu::dpp::append_dpp16_disassembly(out, dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                                          dpp_bound_ctrl_, dpp_fi_, false,
                                          amdgpu::dpp::DppCtrlDialect::Gfx9);
}

void Vop1::implicit_uses(RegisterSet &uses) const {
  bool sdwa_preserve =
      sdwa_dst_sel_ != amdgpu::sdwa::DWORD && sdwa_dst_unused_ == amdgpu::sdwa::UNUSED_PRESERVE;
  bool dpp_partial = inst_.src0 == amdgpu::SRC_DPP &&
                     (dpp_row_mask_ != 0xF || dpp_bank_mask_ != 0xF ||
                      (dpp_bound_ctrl_ == 0 && amdgpu::dpp::dpp_ctrl_produces_oob(dpp_ctrl_)));
  if (sdwa_preserve || dpp_partial)
    for (int i = 0; i < num_dst_operands(); ++i)
      if (const auto *dst = dst_operand(i))
        if (auto ref = dst->to_register_ref())
          if (ref->cls == RegClass::VGPR)
            uses.expand(*ref);
}

bool Vop1::default_encoding() {
  return inst_.src0 != 250 && inst_.src0 != 255 && inst_.src0 != 249;
}

bool Vop1::has_lit() { return inst_.src0 == 255; }

bool Vop1::has_dpp() { return inst_.src0 == 250; }

bool Vop1::has_sdwa() { return inst_.src0 == 249; }

Vopc::Vopc(std::string_view mnemonic, const VopcMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
  std::memcpy(raw_words_.data(), inst, size_);
  raw_encoding_ = raw_words_.data();
}

bool Vopc::default_encoding() {
  return inst_.src0 != 250 && inst_.src0 != 255 && inst_.src0 != 249;
}

bool Vopc::has_lit() { return inst_.src0 == 255; }

bool Vopc::has_sdwa() { return inst_.src0 == 249; }

bool Vop2::has_encoded_dpp() const {
  if (!(inst_.src0 == amdgpu::SRC_DPP))
    return false;
  return (inst_.op >= 0 && inst_.op <= 22) || (inst_.op >= 25 && inst_.op <= 35) ||
         (inst_.op >= 38 && inst_.op <= 61);
}

Vop2::Vop2(std::string_view mnemonic, const Vop2MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (has_encoded_dpp()) {
    owned_mnemonic_ = amdgpu::dpp::dpp_mnemonic(mnemonic, true);
    display_mnemonic_ = owned_mnemonic_;
  }
  if ((!default_encoding() && !(inst_.src0 == amdgpu::SRC_DPP)) || has_encoded_dpp() ||
      hasImpliedLiteral())
    size_ += sizeof(MachineInst);
  if (hasImpliedLiteral())
    literal_ = reinterpret_cast<const uint32_t *>(inst)[1];
  std::memcpy(raw_words_.data(), inst, size_);
  raw_encoding_ = raw_words_.data();
}

void Vop2::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (has_encoded_dpp())
    amdgpu::dpp::append_dpp16_disassembly(out, dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                                          dpp_bound_ctrl_, dpp_fi_, false,
                                          amdgpu::dpp::DppCtrlDialect::Gfx9);
}

void Vop2::implicit_uses(RegisterSet &uses) const {
  bool sdwa_preserve =
      sdwa_dst_sel_ != amdgpu::sdwa::DWORD && sdwa_dst_unused_ == amdgpu::sdwa::UNUSED_PRESERVE;
  bool dpp_partial = inst_.src0 == amdgpu::SRC_DPP &&
                     (dpp_row_mask_ != 0xF || dpp_bank_mask_ != 0xF ||
                      (dpp_bound_ctrl_ == 0 && amdgpu::dpp::dpp_ctrl_produces_oob(dpp_ctrl_)));
  if (sdwa_preserve || dpp_partial)
    for (int i = 0; i < num_dst_operands(); ++i)
      if (const auto *dst = dst_operand(i))
        if (auto ref = dst->to_register_ref())
          if (ref->cls == RegClass::VGPR)
            uses.expand(*ref);
}

bool Vop2::default_encoding() {
  return inst_.src0 != 250 && inst_.src0 != 255 && inst_.src0 != 249;
}

bool Vop2::has_lit() { return inst_.src0 == 255; }

bool Vop2::has_dpp() { return inst_.src0 == 250; }

bool Vop2::has_sdwa() { return inst_.src0 == 249; }

bool Vop2::hasImpliedLiteral() {
  return inst_.op == 23 || inst_.op == 24 || inst_.op == 36 || inst_.op == 37;
}

Vintrp::Vintrp(std::string_view mnemonic, const VintrpMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
  if (!default_encoding())
    size_ += sizeof(MachineInst);
}

bool Vintrp::default_encoding() { return true; }

Vop3p::Vop3p(std::string_view mnemonic, const Vop3pMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Vop3p::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  amdgpu::vop::append_vop3p_disassembly(out, inst->op_sel,
                                        inst->op_sel_hi | (inst->op_sel_hi_2 << 2), inst->neg,
                                        inst->neg_hi, inst->clamp, num_src_operands());
}

bool Vop3::displays_vop3_op_sel() const {
  return (inst_.op >= 20 && inst_.op <= 21) || (inst_.op >= 32 && inst_.op <= 63) ||
         (inst_.op >= 160 && inst_.op <= 191) || (inst_.op >= 287 && inst_.op <= 291) ||
         (inst_.op >= 294 && inst_.op <= 307) || (inst_.op >= 330 && inst_.op <= 331) ||
         (inst_.op >= 377 && inst_.op <= 394) || (inst_.op >= 397 && inst_.op <= 399) ||
         (inst_.op >= 490 && inst_.op <= 492) || (inst_.op >= 494 && inst_.op <= 495) ||
         (inst_.op >= 497 && inst_.op <= 498) || (inst_.op >= 500 && inst_.op <= 508) ||
         (inst_.op >= 515 && inst_.op <= 519) || (inst_.op >= 665 && inst_.op <= 666) ||
         (inst_.op >= 670 && inst_.op <= 672);
}

Vop3::Vop3(std::string_view mnemonic, const Vop3MachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Vop3::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  amdgpu::vop::append_vop3_disassembly(out, inst->op_sel, inst->clamp, inst->omod,
                                       num_src_operands(), displays_vop3_op_sel());
}

void Vop3::append_src_operand(std::string &out, uint8_t operand_index) const {
  const Operand *operand = src_operands_[operand_index];
  const auto reg = operand->to_register_ref();
  const bool half_width = false && operand->size_bits() == 16 && reg && reg->cls == RegClass::VGPR;
  amdgpu::vop::append_vop3_operand(out, operand->name(), (inst_.abs >> operand_index) & 1,
                                   (inst_.neg >> operand_index) & 1, half_width,
                                   (inst_.op_sel >> operand_index) & 1);
}

void Vop3::append_dst_operand(std::string &out, uint8_t operand_index) const {
  const Operand *operand = dst_operands_[operand_index];
  const auto reg = operand->to_register_ref();
  const bool half_width = false && operand->size_bits() == 16 && reg && reg->cls == RegClass::VGPR;
  amdgpu::vop::append_vop3_operand(out, operand->name(), false, false, half_width,
                                   (inst_.op_sel >> 3) & 1);
}

Ds::Ds(std::string_view mnemonic, const DsMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

Mubuf::Mubuf(std::string_view mnemonic, const MubufMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Mubuf::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (inst->offen)
    out += " offen";
  if (inst->idxen)
    out += " idxen";
  if (inst->offset)
    out += " offset:" + std::to_string(inst->offset);
  if (inst->glc)
    out += " glc";
  if (inst->slc)
    out += " slc";
  if (inst->lds)
    out += " lds";
}

Mtbuf::Mtbuf(std::string_view mnemonic, const MtbufMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Mtbuf::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  if (inst->offen)
    out += " offen";
  if (inst->offset)
    out += " offset:" + std::to_string(inst->offset);
  if (inst->glc)
    out += " glc";
  if (inst->slc)
    out += " slc";
}

Mimg::Mimg(std::string_view mnemonic, const MimgMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

Exp::Exp(std::string_view mnemonic, const ExpMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
}

Flat::Flat(std::string_view mnemonic, const FlatMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>("", exec_fn), inst_(*inst),
      owned_mnemonic_(flat_mnemonic(mnemonic, inst->seg)) {
  mnemonic_ = owned_mnemonic_;
  display_mnemonic_ = owned_mnemonic_;
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

void Flat::build_modifiers(std::string &out) const {
  auto *inst = &inst_;
  (void)inst;
  int flat_offset = (inst->seg != 0) ? (inst->offset | (inst->pad_12 << 12)) : inst->offset;
  if (flat_offset)
    out += " offset:" + std::to_string(flat_offset);
  if (inst->glc)
    out += " glc";
  if (inst->slc)
    out += " slc";
}

void Flat::implicit_uses(RegisterSet &uses) const {
  if (inst_.saddr == 0x7F)
    return;
  if (inst_.seg == 1) {
    uses.expand(RegisterRef{RegClass::SGPR, static_cast<uint16_t>(inst_.saddr), 1});
  } else if (inst_.seg == 2) {
    uses.expand(RegisterRef{RegClass::SGPR, static_cast<uint16_t>(inst_.saddr), 2});
  }
}

Vop3SdstEnc::Vop3SdstEnc(std::string_view mnemonic, const Vop3SdstEncMachineInst *inst,
                         ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

Vop3pMfma::Vop3pMfma(std::string_view mnemonic, const Vop3pMfmaMachineInst *inst, ExecuteFn exec_fn)
    : IsaInstruction<Isa>(mnemonic, exec_fn), inst_(*inst) {
  size_ = sizeof(OpEncoding);
  raw_encoding_ = reinterpret_cast<const uint32_t *>(&inst_);
  encoding_id_ = raw_encoding_[0] >> 23;
  opcode_ = inst_.op;
}

} // namespace cdna1
} // namespace rocjitsu
